### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by pishguy** [wal33d006/progress_indicators#4]
sample code not working and after running project i don't see any dot on screen

**Comment by wal33d006** [comment]
@MahdiPishguy 
Sample code works fine at my end. Can you please tell me the specific error? Flutter version?

**Comment by pishguy** [comment]
@wal33d006 

`[√] Flutter (Channel beta, v1.15.17, on Microsoft Windows [Version 6.1.7601]`

**Comment by wal33d006** [comment]
> @wal33d006
> 
> `[√] Flutter (Channel beta, v1.15.17, on Microsoft Windows [Version 6.1.7601]`

Please switch to stable version.

**Comment by pishguy** [comment]
@wal33d006 i don't want, i can't switch because of one library :(

**Comment by wal33d006** [comment]
> @wal33d006 i don't want, i can't switch because of one library :(

If you are working in a production level application, it is recommended to use stable channel.
