### ISSUE TITLE
JumpingDots not Working

### ISSUE THREAD

**Issue by atul-chaudhary** [wal33d006/progress_indicators#5]
`child: JumpingDotsProgressIndicator(
          fontSize: 30.0,
          color: Colors.blue,
          numberOfDots: 5,
        ),`

this is my code snippet, but Jumping dots is not working.

**Comment by jayabrown** [comment]
Can confirm that the dots do not, in fact, jump.

**Comment by wal33d006** [comment]
> `child: JumpingDotsProgressIndicator( fontSize: 30.0, color: Colors.blue, numberOfDots: 5, ),`
> 
> this is my code snippet, but Jumping dots is not working.
That was a bug, now fixed. Please check.

**Comment by wal33d006** [comment]
@atul-chaudhary 
Fixed. Please reopen if this doesn't verify
